"""
CommunityIQ v2
PDF Report Generator

Creates executive decision reports.
"""

import io

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

from reportlab.platypus import (
    Paragraph,
    Spacer,
    SimpleDocTemplate,
    Table,
    TableStyle,
)


styles = getSampleStyleSheet()


title_style = styles["Heading1"]
title_style.alignment = TA_CENTER

heading = styles["Heading2"]

normal = styles["BodyText"]


def generate_pdf(report):

    """
    Generate Executive PDF Report

    Returns
    -------
    bytes
    """

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=0.5 * inch,
        leftMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )

    story = []

    #############################################################
    # Header
    #############################################################

    story.append(
        Paragraph(
            "CommunityIQ",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "AI Powered Decision Intelligence Platform",
            normal,
        )
    )

    story.append(
        Spacer(
            1,
            0.3 * inch,
        )
    )

    #############################################################
    # Executive Summary
    #############################################################

    story.append(
        Paragraph(
            "Executive Summary",
            heading,
        )
    )

    story.append(
        Paragraph(
            report["recommendation"]["executive_summary"],
            normal,
        )
    )

    story.append(
        Spacer(
            1,
            0.25 * inch,
        )
    )

    #############################################################
    # Analysis Table
    #############################################################

    analysis = report["analysis"]

    table_data = [

        ["Area", analysis["area"]],

        ["Priority Score", analysis["priority_score"]],

        ["Risk Band", analysis["risk_band"]],

        ["Primary Driver", analysis["top_driver"]],

        ["Forecast Metric", analysis["forecast_metric"]],

    ]

    table = Table(table_data)

    table.setStyle(

        TableStyle(

            [

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#4285F4")),

                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ]

        )

    )

    story.append(table)

    story.append(
        Spacer(
            1,
            0.3 * inch,
        )
    )

    #############################################################
    # Recommended Actions
    #############################################################

    story.append(
        Paragraph(
            "Recommended Actions",
            heading,
        )
    )

    for action in report["recommendation"]["recommended_actions"]:

        story.append(
            Paragraph(
                f"• {action}",
                normal,
            )
        )

    story.append(
        Spacer(
            1,
            0.25 * inch,
        )
    )

    #############################################################
    # Agent Findings
    #############################################################

    story.append(
        Paragraph(
            "Agent Findings",
            heading,
        )
    )

    for finding in report["recommendation"]["agent_findings"]:

        story.append(
            Paragraph(
                f"• {finding}",
                normal,
            )
        )

    story.append(
        Spacer(
            1,
            0.25 * inch,
        )
    )

    #############################################################
    # Footer
    #############################################################

    story.append(
        Paragraph(
            "<b>Generated By</b>",
            heading,
        )
    )

    story.append(
        Paragraph(
            """
CommunityIQ Multi-Agent Decision Intelligence Platform

Google Gemini

Vertex AI

BigQuery

Streamlit

Report Generated Automatically
""",
            normal,
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf