"""
CommunityIQ v2
Reports Page

Displays the executive report generated by the
multi-agent system and allows PDF export.
"""

import streamlit as st

from agents.orchestrator import orchestrator
from services.pdf_generator import generate_pdf


def show_reports(
    traffic,
    air,
    complaints,
):
    """
    Reports Page
    """

    st.header("📄 Executive Decision Reports")

    st.caption(
        "Generate AI-powered executive reports for decision makers."
    )

    st.divider()

    ##########################################################
    # Inputs
    ##########################################################

    areas = sorted(
        traffic["area"].unique()
    )

    col1, col2 = st.columns([3, 2])

    with col1:

        query = st.text_input(
            "Decision Request",
            value="Generate decision report for T Nagar",
        )

    with col2:

        default_area = st.selectbox(
            "Default Area",
            areas,
            key="reports_default_area",
        )

    st.divider()

    ##########################################################
    # Run Agents
    ##########################################################

    if st.button(
        "🚀 Generate Executive Report",
        use_container_width=True,
    ):

        with st.spinner("Running CommunityIQ AI Agents..."):

            result = orchestrator.execute(
                query=query,
                traffic=traffic,
                air=air,
                complaints=complaints,
                default_area=default_area,
            )

        report = result["report"]

        ##########################################################
        # Planner
        ##########################################################

        st.subheader("🧠 Planner Agent")

        planner = report["planner"]

        c1, c2, c3 = st.columns(3)

        c1.metric(
            "Intent",
            planner["intent"],
        )

        c2.metric(
            "Datasets",
            len(planner["datasets"]),
        )

        c3.metric(
            "Workflow Steps",
            len(planner["workflow"]),
        )

        with st.expander("Execution Plan"):

            st.write("**Query**")

            st.write(planner["query"])

            st.write("**Workflow**")

            for step in planner["workflow"]:

                st.success(step)

        st.divider()

        ##########################################################
        # Analysis
        ##########################################################

        st.subheader("📊 Analysis Agent")

        analysis = report["analysis"]

        a1, a2, a3 = st.columns(3)

        a1.metric(
            "Priority",
            analysis["priority_score"],
        )

        a2.metric(
            "Risk Band",
            analysis["risk_band"],
        )

        a3.metric(
            "Top Driver",
            analysis["top_driver"],
        )

        st.divider()

        ##########################################################
        # Recommendation
        ##########################################################

        st.subheader("🤖 Recommendation Agent")

        recommendation = report["recommendation"]

        st.info(
            recommendation["executive_summary"]
        )

        st.markdown("### Recommended Actions")

        for action in recommendation["recommended_actions"]:

            st.success(action)

        st.markdown("### Agent Findings")

        for finding in recommendation["agent_findings"]:

            st.write(f"• {finding}")

        st.divider()

        ##########################################################
        # Executive Report
        ##########################################################

        st.subheader("📋 Executive Report")

        st.code(
            report["executive_report"],
            language="text",
        )

        ##########################################################
        # PDF
        ##########################################################

        pdf = generate_pdf(
            report
        )

        st.download_button(
            label="📥 Download Executive PDF",
            data=pdf,
            file_name="CommunityIQ_Executive_Report.pdf",
            mime="application/pdf",
            use_container_width=True,
        )

        st.success(
            "Executive report generated successfully."
        )